#THIS IS TO PLACTICE CLASS AND METHODS

##CREATE A BANK CLASS AND METHODTS TO DEPOSIT AND WITHDRAW MONEY FROM THE 
##ACCOUNT, IF THE ACCOUNT DOES NOT HAVE ENOUGH FUND, PREVENT WITHDRAWAL

class Bank_Account(self, deposit, balance =0):
    
    def __init__
